### PR TITLE
Init options from parameter

### PR DESCRIPTION
**Pull request by piotr-gawron**
I implemented initialization of a listbox from list of options passed from JS code.
I added an example in README.RD file so it could be directly copy-pasted.

If you don't like the format please let me know.

I already wrote here some remarks regarding code formatting here: https://github.com/maykinmedia/dual-listbox/pull/17 (I again destroyed it...)

### CODE REVIEW

**Comment by JostCrow** [comment]
@piotr-gawron Can you move this repo into the dual-listbox repository?

**Comment by piotr-gawron** [comment]
What do you mean by moving repo into dual-listbox repository?

Do you wanr me to create branch within your repository (maykinmedia/dual-listbox)?

**Comment by JostCrow** [comment]
Yes that is what i mean. You can now develop all features in the dual listbox branches. This way your changes will be tested

**Comment by JostCrow** [comment]
@piotr-gawron moved this branch to the dual-listbox repo.

**Pull request closed without merging**
