### PR TITLE
Title of the list should not scroll with select elements

### PR DESCRIPTION
**Pull request by piotr-gawron**
Few changes:
* Main change in this PR is as mentioned in title - title shouldn't be scrolled together with elements 
* several typos fixed
* I added myself to contributers as suggested by @svenvandescheur 

One thing that I noticed is missing in the project is code formating standards. I assume that you are using IntelliJ/WebStorm IDE. Can you include in the repository code formating template (my default template is slightly different).

### CODE REVIEW

**Comment by JostCrow** [comment]
@piotr-gawron for the code formatting we now use jshint. https://github.com/maykinmedia/dual-listbox/blob/master/.jshintrc This is the configuration file.

**Comment by svenvandescheur** [comment]
@piotr-gawron @JostCrow For code formatting there is also a ..editorconfig file: http://editorconfig.org/

**Comment by JostCrow** [comment]
@piotr-gawron  This will be closed in favour of #18 since Travis/saucelab testing will always fail.

**Comment by piotr-gawron** [comment]
@JostCrow , @svenvandescheur  
Regarding code formatting, I use Intellij Idea, (which should automatically import .editorconfig) but the config file is not specified in many places and it takes my defaults for code formatting when it cannot find it in the config file.

I also ran jshint. And it doesn't report any problems.

**Comment by JostCrow** [comment]
Searching for editorconfig with Intellij, I got this result. https://plugins.jetbrains.com/plugin/7294-editorconfig. So I think you need to install this plugin.

**Comment by piotr-gawron** [comment]
The plugin is (was) automatically installed together with the IDE itself, so that's not the case.

The difference in our coding style is not covered by your .editorconfig file.

**Pull request closed without merging**
